// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: eventEmitter/eventEmitter.proto

package eventEmitter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventEmitter_AddLogEvent_FullMethodName = "/EventEmitter/AddLogEvent"
)

// EventEmitterClient is the client API for EventEmitter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventEmitterClient interface {
	AddLogEvent(ctx context.Context, in *CreateLogEventRequest, opts ...grpc.CallOption) (*CreateLogEventResponse, error)
}

type eventEmitterClient struct {
	cc grpc.ClientConnInterface
}

func NewEventEmitterClient(cc grpc.ClientConnInterface) EventEmitterClient {
	return &eventEmitterClient{cc}
}

func (c *eventEmitterClient) AddLogEvent(ctx context.Context, in *CreateLogEventRequest, opts ...grpc.CallOption) (*CreateLogEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLogEventResponse)
	err := c.cc.Invoke(ctx, EventEmitter_AddLogEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventEmitterServer is the server API for EventEmitter service.
// All implementations must embed UnimplementedEventEmitterServer
// for forward compatibility.
type EventEmitterServer interface {
	AddLogEvent(context.Context, *CreateLogEventRequest) (*CreateLogEventResponse, error)
	mustEmbedUnimplementedEventEmitterServer()
}

// UnimplementedEventEmitterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventEmitterServer struct{}

func (UnimplementedEventEmitterServer) AddLogEvent(context.Context, *CreateLogEventRequest) (*CreateLogEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLogEvent not implemented")
}
func (UnimplementedEventEmitterServer) mustEmbedUnimplementedEventEmitterServer() {}
func (UnimplementedEventEmitterServer) testEmbeddedByValue()                      {}

// UnsafeEventEmitterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventEmitterServer will
// result in compilation errors.
type UnsafeEventEmitterServer interface {
	mustEmbedUnimplementedEventEmitterServer()
}

func RegisterEventEmitterServer(s grpc.ServiceRegistrar, srv EventEmitterServer) {
	// If the following call pancis, it indicates UnimplementedEventEmitterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventEmitter_ServiceDesc, srv)
}

func _EventEmitter_AddLogEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLogEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventEmitterServer).AddLogEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventEmitter_AddLogEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventEmitterServer).AddLogEvent(ctx, req.(*CreateLogEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventEmitter_ServiceDesc is the grpc.ServiceDesc for EventEmitter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventEmitter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "EventEmitter",
	HandlerType: (*EventEmitterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLogEvent",
			Handler:    _EventEmitter_AddLogEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "eventEmitter/eventEmitter.proto",
}
